### ISSUE TITLE
Incompatible python client and bigchaindb versions

### ISSUE THREAD

**Issue by r7vme** [bigchaindb/kyber#13]
Hello, i've followed README instructions and failed in first example with following error:

```
(venv) tutorials|master ⇒ PYTHONPATH=. BDB_SERVER_URL=http://localhost:49984 python 01_simple_transactions/simple_transactions.py
{'_links': {'api_v1': 'http://localhost:49984/api/v1/', 'docs': 'https://docs.bigchaindb.com/projects/server/en/v0.11.0.dev/'}, 'keyring': [], 'public_key': 'GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4', 'software': 'BigchainDB', 'version': '0.11.0.dev'}
Posting signed transaction{'inputs': [{'owners_before': ['5SYWXZFS7fAK9kE3VhzfrzaikUQScbUxPWGxpUdyTXwb'], 'fulfills': None, 'fulfillment': 'cf:4:QfnlNrmSLpTfKEXqiKAAOMho8C3YyQfjRRpxMoSHy-Y9KtKYvpGOeaFWOaZBly6BX2dTVRxkNDH4f6dPN4CuFuX1mT0LvJKDtEEjHLAHzlXqEc2AtNGupHLXhuc0pnAG'}], 'outputs': [{'public_keys': ['5SYWXZFS7fAK9kE3VhzfrzaikUQScbUxPWGxpUdyTXwb'], 'condition': {'details': {'type': 'fulfillment', 'type_id': 4, 'bitmask': 32, 'public_key': '5SYWXZFS7fAK9kE3VhzfrzaikUQScbUxPWGxpUdyTXwb', 'signature': None}, 'uri': 'cc:4:20:QfnlNrmSLpTfKEXqiKAAOMho8C3YyQfjRRpxMoSHy-Y:96'}, 'amount': 1}], 'operation': 'CREATE', 'metadata': {'metadata_message': 'I am specific to this create transaction'}, 'asset': {'data': {'asset_message': 'I will stick to every future transfer transaction'}}, 'version': '0.9', 'id': '046634977bf5d102e4a8e7488a659a41a7c611968e4467b379049ba4293107b5'}
Traceback (most recent call last):
  File "01_simple_transactions/simple_transactions.py", line 43, in <module>
    bdb.transactions.send(tx_create_alice_simple_signed)
  File "/home/r7vme/src/bigchaindb/kyber/drivers/python/bigchaindb_driver/driver.py", line 305, in send
    method='POST', path=self.path, json=transaction, headers=headers)
  File "/home/r7vme/src/bigchaindb/kyber/drivers/python/bigchaindb_driver/transport.py", line 58, in forward_request
    headers=headers,
  File "/home/r7vme/src/bigchaindb/kyber/drivers/python/bigchaindb_driver/connection.py", line 57, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.BadRequest: (400, '{\n  "message": "Invalid transaction schema: 1 is not of type \'string\'", \n  "status": 400\n}\n', {'message': "Invalid transaction schema: 1 is not of type 'string'", 'status': 400})
```

I found that python client version is [0.2.1](https://github.com/bigchaindb/kyber/blob/master/drivers/python/setup.py#L45) , which has bigchaindb dependency [0.9.1](https://github.com/bigchaindb/kyber/blob/master/drivers/python/setup.py#L14). But git submodule with bigchaindb checked out on at least 0.10

```
kyber|master ⇒ git submodule status
 b4417935508e7d4f6914c1ac84240113d99ea001 bigchaindb-server (v0.10.0-94-gb4417935)
```

Workaround that i use:
```
cd bigchaindb-server
git co v0.9.5
cd ..
```

Restart docker-compose
```
docker rmi kyber_bdb-server
make stop
make
```

After that i was able to run python tutorial example
```
PYTHONPATH=. BDB_SERVER_URL=http://localhost:49984 python 01_simple_transactions/simple_transactions.py
```

**Comment by ttmc** [comment]
This repository (bigchaindb/kyber) contains examples that worked with older versions of BigchainDB, but the stuff in this repository hasn't been maintained and the examples almost certainly won't work with newer versions of BigchainDB. Therefore we are closing all the old issues, marking the repo as old/not-supported, and archiving the repo. You can find newer examples in other places.
