### ISSUE TITLE
Error on "make":ImportError: cannot import name 'ThresholdSha256Fulfillment'

### ISSUE THREAD

**Issue by eshnil2000** [bigchaindb/kyber#18]
Step 13/13 : RUN bigchaindb -y configure mongodb
 ---> Running in 32c9cd0f8288
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/src/app/bigchaindb/__init__.py", line 100, in <module>
    from bigchaindb.core import Bigchain  # noqa
  File "/usr/src/app/bigchaindb/core.py", line 10, in <module>
    from bigchaindb import backend, config_utils, fastquery
  File "/usr/src/app/bigchaindb/config_utils.py", line 28, in <module>
    from bigchaindb.consensus import BaseConsensusRules
  File "/usr/src/app/bigchaindb/consensus.py", line 1, in <module>
    from bigchaindb.models import Transaction
  File "/usr/src/app/bigchaindb/models.py", line 8, in <module>
    from bigchaindb.common.transaction import Transaction
  File "/usr/src/app/bigchaindb/common/transaction.py", line 4, in <module>
    from cryptoconditions import (Fulfillment, ThresholdSha256Fulfillment,
ImportError: cannot import name 'ThresholdSha256Fulfillment'
ERROR: Service 'bdb-server' failed to build: The command '/bin/sh -c bigchaindb -y configure mongodb' returned a non-zero code: 1
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by jonas-pietzsch** [comment]
Same problem here. 

Docker version: `Docker version 18.03.1-ce, build 9ee9f40`
Docker-compose version: `docker-compose version 1.21.1, build 5a3f1a3`
OS: `MacOS 10.12.6`

**Comment by ttmc** [comment]
I think the problem is that this is an old repository that doesn't work with the latest changes to BigchainDB. I'll check with the team. If it is, in fact, defunct, then we should really make that more obvious.

**Comment by ttmc** [comment]
This repository (bigchaindb/kyber) contains examples that worked with older versions of BigchainDB, but the stuff in this repository hasn't been maintained and the examples almost certainly won't work with newer versions of BigchainDB. Therefore we are closing all the old issues, marking the repo as old/not-supported, and archiving the repo. You can find newer examples in other places.
